name: Mi Primer WorkFlow
on: 
  push:
    branches: [ main ]
       

jobs:
  tarea_0:
  
    runs-on: ubuntu-latest

    steps:
 
      - name: Saludar con echo
        run: echo "Hola gitHub actions"
      
