name: My First WorkFlow
on: 
  push:
    branches: [ main ]
       

jobs:
  task_0:
  
    runs-on: ubuntu-latest

    steps:

      - name: "Copy repo to VM"
        uses: actions/checkout@v2

      - name: "Run Multi Lines"
        run: | 
          echo "Hello x"
          python --version

      - name: "Print files"
        run: ls -l
      
