name: My First WorkFlow
on: 
  push:
    branches: [ main ]
       

jobs:
  task_0:
  
    runs-on: ubuntu-latest

    steps:
 
      - name: "Run Multi Lines"
        run: | 
        echo "Hello gitHub"
        python --version
          
      
