name: Hola Python
on: 
  push:
    branches: 
      - master
       

jobs:
  build_2:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Comandos multiples II
        run: | 
         python --version
         python tests.py
      
