name: Hola Python
on: 
  push:
    branches: 
      - main
       

jobs:
  build_3:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python Tests 
        run: | 
         python --version
         python tests.py
      
