name: Hola Python
on: push

jobs:
  build_2:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Comandos multiples II
        run: | 
         python --version
         python file.py
      
