name: Hola Python
on: push

jobs:
  build_2:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Comandos multiples
        run: python -v && python file.py
      
