name: Hola Node
on: 
  push:
    branches: [ main, dev]
       

jobs:
  build_4:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Hello Node
        run: | 
         node --version
         python test.py
      
