name: My First WorkFlow
on: 
  push:
    branches: [ main ]
       

jobs:
  task_0:
  
    runs-on: ubuntu-latest

    steps:
 
      - name: "Greetings with echo"
        run: echo "Hello gitHub"
        
      - name: "Show python version"
      	run: python --version
        
      
