name: My Pipeline Workflow

on: 
  push:
    branches: ["main"]


jobs:
	tarea1: 
		runs-on: ubuntu-latest
		steps:
			- run: echo "Hello from tarea1"	
	
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Copy repo on the VM"
        uses: actions/checkout@v2

      - name: 'Node environment'
        uses: actions/setup-node@v2
        
      - name: 'Install  Node dependencies'
        run: "npm install --no-audit --no-fund --no-optional"

      - name: 'Show node version'
        run: 'node --version'

      - name: 'Run Tests'
        run: 'npm run test'

      - name: "Linter"
        run: 'npm run lint'
      
