name: My Pipeline Workflow

on: 
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Copy repo on the VM"
        uses: actions/checkout@v2

      - name: 'Node environment'
        uses: actions/setup-node@v2
        
      - name: 'Install dependencies'
        run: "npm install"

      - name: 'Show node version'
        run: 'node --version'

      - name: 'Run Tests'
        run: 'npm run test'
      
